"""Initial migration with all models

Revision ID: 0c00cb7b7f78
Revises: 
Create Date: 2026-01-08 15:59:51.902951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c00cb7b7f78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module', sa.Enum('CARDIOTHORACIC_VASCULAR', 'MUSCULOSKELETAL_TRAUMA', 'GASTROINTESTINAL', 'GENITOURINARY_BREAST', 'PAEDIATRIC', 'CNS_HEAD_NECK', name='frcrmodule'), nullable=True))
        batch_op.add_column(sa.Column('body_part', sa.Enum('BRAIN', 'SPINE', 'HEAD_NECK', 'THORAX', 'CARDIOVASCULAR', 'CHEST_WALL', 'UPPER_LIMB', 'LOWER_LIMB', 'ABDOMEN_BOWEL', 'LIVER', 'GALLBLADDER', 'BILIARY_TREE', 'PANCREAS', 'SPLEEN', 'URINARY_SYSTEM', 'REPRODUCTIVE_SYSTEM', 'BREAST', 'PAEDIATRIC_GENERAL', 'PAEDIATRIC_SKELETON', 'PAEDIATRIC_CHEST', 'PAEDIATRIC_CONGENITAL', name='bodypart'), nullable=True))
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('packet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('case_number',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_case_body_part'), ['body_part'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_is_public'), ['is_public'], unique=False)
        batch_op.create_index(batch_op.f('ix_case_module'), ['module'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['created_by_user_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_case_module'))
        batch_op.drop_index(batch_op.f('ix_case_is_public'))
        batch_op.drop_index(batch_op.f('ix_case_body_part'))
        batch_op.alter_column('case_number',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('packet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('is_public')
        batch_op.drop_column('body_part')
        batch_op.drop_column('module')

    # ### end Alembic commands ###
