"""Add AI diagnosis cache and content verification

Revision ID: 167ef09c7b85
Revises: 2aaf03533001
Create Date: 2026-01-16 20:11:17.820313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167ef09c7b85'
down_revision = '2aaf03533001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create ai_diagnosis_cache table (if it doesn't exist)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'ai_diagnosis_cache' not in tables:
        op.create_table('ai_diagnosis_cache',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('diagnosis', sa.String(length=500), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('first_case_id', sa.Integer(), nullable=False),
        sa.Column('first_user_id', sa.Integer(), nullable=False),
        sa.Column('first_generated_at', sa.DateTime(), nullable=False),
        sa.Column('query_count', sa.Integer(), nullable=False),
        sa.Column('last_queried_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['first_case_id'], ['case.id'], ),
        sa.ForeignKeyConstraint(['first_user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('diagnosis', 'provider', 'model_name', name='uq_diagnosis_provider_model')
        )
        op.create_index(op.f('ix_ai_diagnosis_cache_diagnosis'), 'ai_diagnosis_cache', ['diagnosis'], unique=False)
        op.create_index(op.f('ix_ai_diagnosis_cache_first_case_id'), 'ai_diagnosis_cache', ['first_case_id'], unique=False)
    
    # Add ai_content_verified to case table (if it doesn't exist)
    case_columns = [col['name'] for col in inspector.get_columns('case')]
    if 'ai_content_verified' not in case_columns:
        # Use regular alter_table to avoid foreign key reflection issues
        op.add_column('case', sa.Column('ai_content_verified', sa.Boolean(), nullable=False, server_default='0'))
        op.create_index('ix_case_ai_content_verified', 'case', ['ai_content_verified'], unique=False)
    
    # Note: Legacy table drops (candidate, exam_session, packet) and packet_id column
    # are skipped here to avoid foreign key reflection issues. These can be cleaned up
    # in a separate migration if needed, or the tables can be dropped manually.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop ai_diagnosis_cache table
    op.drop_index(op.f('ix_ai_diagnosis_cache_first_case_id'), table_name='ai_diagnosis_cache')
    op.drop_index(op.f('ix_ai_diagnosis_cache_diagnosis'), table_name='ai_diagnosis_cache')
    op.drop_table('ai_diagnosis_cache')
    
    # Remove ai_content_verified from case table
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_ai_content_verified'))
        batch_op.drop_column('ai_content_verified')

    op.create_table('packet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exam_id', sa.INTEGER(), nullable=False),
    sa.Column('packet_number', sa.INTEGER(), nullable=False),
    sa.Column('packet_id', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('exam_date', sa.DATE(), nullable=False),
    sa.Column('exam_time', sa.VARCHAR(length=10), nullable=False),
    sa.Column('session_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('exam_id', sa.INTEGER(), nullable=False),
    sa.Column('candidate_name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('candidate_number', sa.INTEGER(), nullable=False),
    sa.Column('packet_number', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
