"""Add cancelled fields to AdminApprovalCode

Revision ID: 2600c2e4df95
Revises: 827ea200f794
Create Date: 2026-01-25 15:15:02.035572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2600c2e4df95'
down_revision = '827ea200f794'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_approval_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_admin_approval_code_cancelled'), ['cancelled'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['cancelled_by_user_id'], ['id'])

    with op.batch_alter_table('ajcc_disease_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frcr_module', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('frcr_body_part', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('frcr_age_group', sa.String(length=50), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_is_superadmin'), ['is_superadmin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_superadmin'))

    with op.batch_alter_table('ajcc_disease_site', schema=None) as batch_op:
        batch_op.drop_column('frcr_age_group')
        batch_op.drop_column('frcr_body_part')
        batch_op.drop_column('frcr_module')

    with op.batch_alter_table('admin_approval_code', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_admin_approval_code_cancelled'))
        batch_op.drop_column('cancelled_by_user_id')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled')

    # ### end Alembic commands ###
