"""Add curated TNM data fields to AJCCStagingData

Revision ID: 43891be57ccb
Revises: 2600c2e4df95
Create Date: 2026-01-25 18:49:45.513302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43891be57ccb'
down_revision = '2600c2e4df95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create index only if not present (2600c2e4df95 may have already created it).
    # Using raw SQL avoids raising in PostgreSQL, which would abort the transaction.
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_admin_approval_code_cancelled "
        "ON admin_approval_code (cancelled)"
    )

    # Idempotent: add columns/index/FK only if missing (Neon may have them from a partial run).
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        op.execute("ALTER TABLE ajcc_staging_data ADD COLUMN IF NOT EXISTS curated_quick_reference_html TEXT")
        op.execute("ALTER TABLE ajcc_staging_data ADD COLUMN IF NOT EXISTS curated_explanatory_notes_html TEXT")
        op.execute("ALTER TABLE ajcc_staging_data ADD COLUMN IF NOT EXISTS is_curated BOOLEAN")
        op.execute("ALTER TABLE ajcc_staging_data ADD COLUMN IF NOT EXISTS curated_by_user_id INTEGER")
        op.execute("ALTER TABLE ajcc_staging_data ADD COLUMN IF NOT EXISTS curated_at TIMESTAMP")
        op.execute(
            "CREATE INDEX IF NOT EXISTS ix_ajcc_staging_data_is_curated "
            "ON ajcc_staging_data (is_curated)"
        )
        op.execute("""
            DO $$
            BEGIN
              IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE constraint_name = 'fk_ajcc_staging_curated_by'
                  AND table_name = 'ajcc_staging_data'
              ) THEN
                ALTER TABLE ajcc_staging_data
                ADD CONSTRAINT fk_ajcc_staging_curated_by
                FOREIGN KEY (curated_by_user_id) REFERENCES "user"(id);
              END IF;
            END $$
        """)
    else:
        # SQLite: use batch_alter_table (no IF NOT EXISTS for columns)
        with op.batch_alter_table('ajcc_staging_data', schema=None) as batch_op:
            batch_op.add_column(sa.Column('curated_quick_reference_html', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('curated_explanatory_notes_html', sa.Text(), nullable=True))
            batch_op.add_column(sa.Column('is_curated', sa.Boolean(), nullable=True))
            batch_op.add_column(sa.Column('curated_by_user_id', sa.Integer(), nullable=True))
            batch_op.add_column(sa.Column('curated_at', sa.DateTime(), nullable=True))
            batch_op.create_index('ix_ajcc_staging_data_is_curated', ['is_curated'], unique=False)
            batch_op.create_foreign_key('fk_ajcc_staging_curated_by', 'user', ['curated_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ajcc_staging_data', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ajcc_staging_curated_by', type_='foreignkey')
        batch_op.drop_index('ix_ajcc_staging_data_is_curated')
        batch_op.drop_column('curated_at')
        batch_op.drop_column('curated_by_user_id')
        batch_op.drop_column('is_curated')
        batch_op.drop_column('curated_explanatory_notes_html')
        batch_op.drop_column('curated_quick_reference_html')

    try:
        with op.batch_alter_table('admin_approval_code', schema=None) as batch_op:
            batch_op.drop_index('ix_admin_approval_code_cancelled')
    except Exception:
        pass

    # ### end Alembic commands ###
