"""Add superadmin flag and AdminApprovalCode table

Revision ID: 827ea200f794
Revises: f9e799abaf7d
Create Date: 2026-01-25 12:28:01.455911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827ea200f794'
down_revision = 'f9e799abaf7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superadmin', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_is_superadmin'), ['is_superadmin'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_is_superadmin'))
        batch_op.drop_column('is_superadmin')

    # ### end Alembic commands ###
