"""Update FRCRModule, BodyPart enums and add AgeGroup enum with age_group field to Case

Revision ID: 85465bd3e9d5
Revises: 0001_initial_schema
Create Date: 2026-01-09 18:31:26.463045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85465bd3e9d5'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('age_group', sa.Enum('ADULT', 'PEDIATRIC', name='agegroup'), nullable=True))
        batch_op.alter_column('body_part',
               existing_type=sa.VARCHAR(length=21),
               type_=sa.Enum('CARDIOVASCULAR', 'LUNG_MEDIASTINUM', 'CHEST_WALL', 'GASTROINTESTINAL', 'HEPATOPANCREATICOBILIARY', 'ADRENAL', 'THYROID_PARATHYROID', 'SPLEEN', 'KUB', 'GYNAECOLOGY', 'BREAST', 'UPPER_LIMB', 'LOWER_LIMB', 'BONES', 'BRAIN_PITUITARY', 'SPINE', 'HEAD_NECK', 'MULTISYSTEM', name='bodypart'),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_case_age_group'), ['age_group'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('case', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_case_age_group'))
        batch_op.alter_column('body_part',
               existing_type=sa.Enum('CARDIOVASCULAR', 'LUNG_MEDIASTINUM', 'CHEST_WALL', 'GASTROINTESTINAL', 'HEPATOPANCREATICOBILIARY', 'ADRENAL', 'THYROID_PARATHYROID', 'SPLEEN', 'KUB', 'GYNAECOLOGY', 'BREAST', 'UPPER_LIMB', 'LOWER_LIMB', 'BONES', 'BRAIN_PITUITARY', 'SPINE', 'HEAD_NECK', 'MULTISYSTEM', name='bodypart'),
               type_=sa.VARCHAR(length=21),
               existing_nullable=True)
        batch_op.drop_column('age_group')

    # ### end Alembic commands ###
