"""Add FRCR mapping fields to AJCCDiseaseSite

Revision ID: f9e799abaf7d
Revises: add_intelligent_tnm_data
Create Date: 2026-01-24 17:11:08.195381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e799abaf7d'
down_revision = 'add_intelligent_tnm_data'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ajcc_disease_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frcr_module', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('frcr_body_part', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('frcr_age_group', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ajcc_disease_site', schema=None) as batch_op:
        batch_op.drop_column('frcr_age_group')
        batch_op.drop_column('frcr_body_part')
        batch_op.drop_column('frcr_module')

    # ### end Alembic commands ###
